// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserServices.proto

package Services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//import "Models.proto";
type UserModel struct {
	UserId               int32                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPwd              string               `protobuf:"bytes,3,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	UserDate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=user_date,json=userDate,proto3" json:"user_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214e495ba750a83, []int{0}
}

func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (m *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(m, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserModel) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserModel) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

func (m *UserModel) GetUserDate() *timestamp.Timestamp {
	if m != nil {
		return m.UserDate
	}
	return nil
}

type RegResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegResponse) Reset()         { *m = RegResponse{} }
func (m *RegResponse) String() string { return proto.CompactTextString(m) }
func (*RegResponse) ProtoMessage()    {}
func (*RegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214e495ba750a83, []int{1}
}

func (m *RegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegResponse.Unmarshal(m, b)
}
func (m *RegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegResponse.Marshal(b, m, deterministic)
}
func (m *RegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegResponse.Merge(m, src)
}
func (m *RegResponse) XXX_Size() int {
	return xxx_messageInfo_RegResponse.Size(m)
}
func (m *RegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegResponse proto.InternalMessageInfo

func (m *RegResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserModel)(nil), "Services.UserModel")
	proto.RegisterType((*RegResponse)(nil), "Services.RegResponse")
}

func init() { proto.RegisterFile("UserServices.proto", fileDescriptor_6214e495ba750a83) }

var fileDescriptor_6214e495ba750a83 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x3e, 0x9a, 0xe6, 0xb2, 0x1d, 0x02, 0x42, 0x18, 0x88, 0x3a, 0x65, 0x72, 0xa5,
	0x22, 0xc4, 0xc8, 0xd2, 0x85, 0x01, 0x84, 0x0c, 0xcc, 0x95, 0x8b, 0x0f, 0x2b, 0x52, 0x5d, 0x47,
	0x39, 0x87, 0xfe, 0x12, 0xfe, 0x2f, 0x8a, 0x53, 0x97, 0x6e, 0x79, 0xde, 0x8b, 0x5f, 0x3f, 0x3e,
	0xc0, 0x4f, 0xa6, 0xee, 0x9d, 0xba, 0x9f, 0xe6, 0x8b, 0x58, 0xb4, 0x9d, 0xf3, 0x0e, 0xa7, 0x91,
	0xcb, 0x3b, 0xe3, 0x9c, 0xd9, 0xd0, 0x3c, 0xe4, 0xeb, 0xfe, 0x7b, 0xee, 0x1b, 0x4b, 0xec, 0x95,
	0x6d, 0xc7, 0x5f, 0x67, 0xbf, 0x09, 0x64, 0x43, 0xc3, 0x8b, 0xd3, 0xb4, 0xc1, 0x6b, 0x48, 0x7b,
	0xa6, 0x6e, 0xd5, 0xe8, 0x22, 0xa9, 0x92, 0xfa, 0x5c, 0x4e, 0x06, 0x7c, 0xd6, 0x78, 0x0b, 0x59,
	0x18, 0x6c, 0x95, 0xa5, 0xe2, 0xa4, 0x4a, 0xea, 0x4c, 0x4e, 0x87, 0xe0, 0x55, 0x59, 0xc2, 0x1b,
	0x08, 0xdf, 0xab, 0x76, 0xa7, 0x8b, 0xd3, 0x30, 0x0b, 0x2d, 0x6f, 0x3b, 0x8d, 0x8f, 0xfb, 0x73,
	0x5a, 0x79, 0x2a, 0xce, 0xaa, 0xa4, 0xce, 0x17, 0xa5, 0x18, 0x9d, 0x44, 0x74, 0x12, 0x1f, 0xd1,
	0x69, 0xec, 0x5c, 0x2a, 0x4f, 0xb3, 0x27, 0xc8, 0x25, 0x19, 0x49, 0xdc, 0xba, 0x2d, 0x13, 0x5e,
	0xc1, 0x84, 0xbd, 0xf2, 0x3d, 0x07, 0xaf, 0x4c, 0xee, 0x09, 0x0b, 0x48, 0x2d, 0x31, 0x2b, 0x13,
	0xad, 0x22, 0x2e, 0x96, 0x90, 0x1f, 0x6d, 0x06, 0x1f, 0x20, 0x1d, 0x50, 0x92, 0xc1, 0x0b, 0x71,
	0x58, 0xd7, 0xe1, 0xe5, 0xe5, 0xe5, 0x7f, 0x78, 0x74, 0xef, 0x7a, 0x12, 0x24, 0xef, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0xdb, 0xac, 0x63, 0x66, 0x01, 0x00, 0x00,
}
